name: Docker Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build test Docker image
      run: |
        cat > Dockerfile.test << 'EOF'
        FROM ubuntu:24.04
        
        ENV DEBIAN_FRONTEND=noninteractive
        ENV DISPLAY=:99
        
        # Install GNOME Shell and dependencies
        RUN apt-get update && apt-get install -y \
            gnome-shell \
            gnome-shell-extensions \
            gjs \
            xvfb \
            dbus-x11 \
            gnome-session \
            mutter \
            gir1.2-gtk-4.0 \
            gir1.2-adw-1 \
            gir1.2-glib-2.0 \
            libglib2.0-dev \
            x11-utils \
            python3 \
            git \
            && rm -rf /var/lib/apt/lists/*
        
        # Create test user
        RUN useradd -m -s /bin/bash testuser
        
        # Copy extension files
        WORKDIR /home/testuser/extension
        COPY --chown=testuser:testuser . .
        
        # Switch to test user
        USER testuser
        
        # Compile schemas
        RUN glib-compile-schemas ./schemas/
        
        # Create test script
        RUN echo '#!/bin/bash\n\
        set -e\n\
        echo "Starting virtual display..."\n\
        Xvfb :99 -screen 0 1920x1080x24 &\n\
        sleep 2\n\
        \n\
        echo "Testing extension installation..."\n\
        mkdir -p ~/.local/share/gnome-shell/extensions/\n\
        ln -s $(pwd) ~/.local/share/gnome-shell/extensions/minimize-dimmer@leobenkel.com\n\
        \n\
        echo "Running basic validation..."\n\
        gjs -c "import(\"./extension.js\").then(() => console.log(\"✓ Extension syntax valid\")).catch(e => {console.error(e); process.exit(1)})"\n\
        \n\
        echo "✓ All tests passed"\n\
        ' > run_tests.sh && chmod +x run_tests.sh
        
        CMD ["./run_tests.sh"]
        EOF
        
        docker build -t minimize-dimmer-test -f Dockerfile.test .
        
    - name: Run tests in Docker
      run: |
        docker run --rm minimize-dimmer-test
        
    - name: Test packaging
      run: |
        # Create a package for distribution
        mkdir -p dist
        zip -r dist/minimize-dimmer.zip \
          metadata.json \
          extension.js \
          prefs.js \
          schemas/ \
          -x "*.git*" \
          -x "*node_modules*" \
          -x "dist/*"
        
        echo "✓ Extension package created: $(ls -lh dist/minimize-dimmer.zip | awk '{print $5}')"
        
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: dist/minimize-dimmer.zip